---
tite: 'Terminal Commands'
---

# Convert Excel File into textfile

We are using following [dataset](https://naehrwertdaten.ch/de/downloads/) and MAC terminal.


Next we convert the excel file into a csv file

- Change directory in terminal the folder containing excel file

ssconvert Schweizer_Nahrwertdatenbank.xlsx newfile.csv


We check the first three lines of s_nw.csv with 

- `$ head -n 3 newfile.csv`

Since the first two lines are not needed we delete them for further processing

- `sed -i '' '1,2d' newfile.csv` ('' after i is for mac terminal)

With excel we explore which column we need for our dashboard: 

- 4: name of product
- 6: category of product
- 8: unit
- 9: energy (kJ)
- 12: energy, calories (kcal)
- 15: fett, total(g)
- 18: fettsäure, gesättigt(g)
- 21: fettsäure, einfach ungesättigt(g)
- 24: fettsäure, mehrfach ungesättigt(g)
- 27: cholesterin (mg)
- 30: kohlenhydrate, verfügbar(g)
- 33: zucker(g)
- 36: stärke (g)
- 39: nahrungsfasern(g)
- 42: Protein (g)
- 45: salz (g)
- 48: alkohol(g)
- 51: wasser (g)
- 54: Vitamin A-Aktivität, RE (µg-RE)
- 57: Vitamin A-Aktivität, RAE (µg-RE)
- 60: Retinol (µg)
- 63: Betacarotin-Aktivität (µg-BCE)
- 66: Betacarotin (µg)
- 69: Vitamin B1 (Thiamin) (mg)
- 72: Vitamin B2 (Riboflavin) (mg)
- 75: Vitamin B6 (Pyridoxin) (mg)
- 78: Vitamin B12 (Cobalamin) (µg)
- 81: Niacin (mg)
- 84: Folat (µg)
- 87: Pantothensäure (mg)
- 90: Vitamin C (Ascorbinsäure) (mg)
- 93: Vitamin D (Calciferol) (µg) 
- 96: Vitamin E (α-Tocopherol) (mg)
- 99: Kalium (K) (mg)
- 102: Natrium (Na) (mg)
- 105: Chlorid (Cl) (mg)
- 108: Calcium (Ca) (mg)
- 111: Magnesium (Mg) (mg)
- 114: Phosphor (P) (mg)
- 117: Eisen (Fe) (mg)
- 120: Jod (I) (µg)
- 123: Zink (Zn)  (mg)
- 126: Selen (Se) (µg)

Since we have some columns with format "...,..." (e.g, energy, calories(csv)) cut command would lead to problems so we use csvcut


`csvcut -c 4,6,8,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,99,102,105,108,111,114,117,120,123,126 newfile.csv > newfile_cut.csv`

Next we want to replace all occurencs of str *k.a.* (keine Angaben) and *Sp.* with NULL so tableau doesn't confuse such coloumns as string columns 

`sed -E  's/n\.d\./NULL/g' swiss_food_cut.csv > final.csv`

`sed -E 's/tr\./0/g' final_cut_k_test.csv > final_cut_k_test2.csv`

`sed -E -i '' 's/[<>]//g' final_cut_k_test2.csv`

`sed 's/"\([0-9]*\),\([0-9]*\)"/\1.\2/g' final_3.csv > output_1.csv`






