project:
  type: website
  output-dir: docs


website:
  title: "Oliver Zingg"
  favicon: "oli.jpg"
  page-navigation: true
  page-footer:
    background: "#000000"
    center:  
      - href: https://github.com/oli9402
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/oliver_zingg
        icon: twitter
        aria-label: Twitter
      - href: https://www.linkedin.com/in/oliver-zingg-321b0228a/
        icon: linkedin
        aria-label: LinkedIn
  navbar:
    background: "#f0eeeb"
    title: 'Oliver Zingg'
    collapse-below: lg
    pinned: true
    right:
      - icon: house-door
        href: index.qmd
        text: Home
      - icon: file-person
        href: about.qmd
      - icon: list-task
        href: projects.qmd
      - icon: book-half
        text: Wiki
        href: wiki.qmd
       
  sidebar: 
      - title: "Wiki"
        style: "docked"
        background: light
        contents:
         - href: wiki.qmd
           text: 'Personal Wiki'
         - text: '------'
         - section: 'Python'
           href: wiki/Python/python_start.qmd
           contents:
             - text: 'Basics'
               href: wiki/Python/basics.qmd
             - text: 'Wrangling'
               href: wiki/Python/wrangling.qmd
             - text: 'Retrueval Augmented Generation'
               href: wiki/Python/rag.qmd
         - section: 'Statistics'
           href: wiki/Statistics/stats_start.qmd
           contents: 
           - text: 'Confidence Intervals'
             href: wiki/Statistics/ci.qmd
         - section: 'Linear Algebra'
           href: wiki/LinAlg/linalg_start.qmd
           contents:
            - text: 'Things to remember'
              href: wiki/LinAlg/ttr.qmd
            - text: 'Systems of Linear Equations'
              href: wiki/LinAlg/sys.qmd
            - text: 'Basis'
              href: wiki/LinAlg/basis.qmd
            - text: 'Linear Maps'
              href: wiki/LinAlg/linear-maps.qmd
            - text: 'Eigenvalues and -vectors'
              href: wiki/LinAlg/eigen.qmd
            - text: 'Orthonormal Basis'
              href: wiki/LinAlg/norm.qmd
         - section: 'Design of Experiments' 
           href: wiki/DOE/int.qmd
           contents:
           - text: 'Research Design'
             href: wiki/DOE/doe.qmd
        
format:
  html:
    toc: true
    code-link: true
    code-fold: true
    mainfont: Poltawski Nowy
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
    highlight-style: breeze
    theme: [Lux, rwds.scss]
    smooth-scroll: true
    anchor-sections: true


execute: 
  freeze: auto