project:
  type: website
  output-dir: docs
 

website:
  title: "Oliver Zingg"
  favicon: "oli.jpg"
  page-navigation: true
  page-footer:
    background: "#000000"
    left: |
      Created by Oliver Zingg with Quarto and RStudio
    center:  
      - href: https://github.com/oli9402
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/oliver_zingg
        icon: twitter
        aria-label: Twitter
      - href: https://www.linkedin.com/in/oliver-zingg-321b0228a/
        icon: linkedin
        aria-label: LinkedIn
    right: |
      Viel Spass beim durchstöbern meiner Seite
  navbar:
    background: "#f0eeeb"
    title: 'Oliver Zingg'
    collapse-below: lg
    pinned: true
    right:
      - icon: house-door
        href: index.qmd
        text: Home
      - icon: file-person
        href: about.qmd
      - icon: list-task
        href: projects.qmd
      - icon: file-earmark
        href: CV.qmd
      - icon: book-half
        text: Wiki
        href: wiki.qmd
       
  sidebar: 
      - title: "Wiki"
        style: "docked"
        background: light
        contents:
         - href: wiki.qmd
           text: 'Personal Wiki'
         - text: '------'
         - section: 'Python'
           href: wiki/Python/python_start.qmd
           contents:
             - text: 'Basics'
               href: wiki/Python/basics.qmd
             - text: 'Wrangling'
               href: wiki/Python/wrangling.qmd
         - section: 'Statistics'
           href: wiki/Statistics/stats_start.qmd
           contents: 
           - text: 'Confidence Intervals'
             href: wiki/Statistics/ci.qmd
        
format:
  html:
    toc: true
    code-link: true
    code-fold: true
    font-family: monospace
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
    highlight-style: breeze

execute: 
  freeze: auto