project:
  type: website
  output-dir: docs
  resources: "_presi.html"

website:
  title: "Oliver Zingg"
  favicon: "oli.jpg"
  navbar:
    background: primary
    pinned: True
    left:
      - icon: house-door
        href: index.qmd
        text: Home
      - icon: file-person
        href: about.qmd
      - icon: list-task
        href: projects.qmd
    tools:
      - icon: code-slash
        href: https://github.com/oli9402/Portfolio
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true
    code-fold: show
    highlight-style: breeze
editor: visual

