---
title: 'Questionnaires' 
---
# Attitude Questions

Definition:

- In theory, not verifiable by external observation or records.
- Has evaluative component
- How strong agree or disagree
- In contrast to beliefs (cognitive component): How healthy is a pizza?
- In contrast to behavioral intentions: In the next 6 months, how likely is it that you will buy a car 


## Traditional View on Attitude 
A psychological tendecy that is expressed by evaluating a particular entity with some degree of favor or disfavor

Attitudes are Pre-existing:
- Automatic activation of attitudes (retrievable: "file-drawer")
- stable and predictive of behaviors, resistant to persuasion

### Problems of traditional view
In survey big differences are found depending on how question is asked.

## Alternative View
"Making it up as you go along"

- individuals do not typically possess true attitudes rather they construct opinion statements on the fly based on whatever considerations are momentarily salient 

Schwarz 2007: evaluative judgments formed on the spot rather than as trait-like dispositions

## Rasinksi's way: Resovling these Divergent views

Attitudes vs. attitude expressions

- Any single attitude measure will be an imperfect reflection of the underlying attitude 
- Attitudes are unobservable, global evaluations of objects

Some attitude expressions are construced on the spot, some are retrieved almost entirely intact from memory, others are a combination.

## Schwarz Resolving
No attitudes, but contextualized construction of evaluations/judgments on the spot drawing on what is available to Respondent (R)

- Stable attitudes = similar evalutions arising from R drwaing on similar inputs or the sam chronically accessible information. 
- Strong attitudes = R drawing on highly accessible information
-Context effects = R drawing on contexutal information when constructing evaluations
-Nonattitude = Same number of conflicting information accessible to R at the same time

## Context Effects 

- Subject of questionnaire
- Interviewer
- Interview setting
- Instructions
- Pictures that accompany the question
- Wording of the question
- Response options 
- Question order

### Context Effects: Comprehension

- Assimilation effects: Rs include prior question in interpreting/understanding the current item 
- Contrast effects: Rs exclude prior questions in interpreting and understanding the current item 

### Conetxt Effects: Retrieval
Context prompts the accessibility or retrieval of certain considerations (assimilation) or exclude the retrieval of certain considerations (contrast)

### Context Effects: Judgement 
The inclusion/exclusion model 
Constructing targets and standards 



## Specific vs. General Evaluations 

Only ask specific question and if general question then asked them first. 

## Agree Disagree Scales (should be avoided)

### Advantages
Fast for R
Fewer "don't know"
R like these scales

### Disadvantages
Acquiesence Bias
- R wants to be polite and agreeable
- R might defer to higher status (yes sure)
- R adopts a satisficing strategy (do just enough)

Multi-barrled 
- multi information in statement 

Disagree end is ambigious 

## Construct-specific repsonse choices (Recommended)

How certain are you of your views on abortion? 
- Very certain, somewhat certain, not very certain, not certain at all

## Don't Know Option?










