---
title: 'Basis, Span, Dimensions'
toc: false
format:
  html:
    mermaid:
      theme: default
---

## Overview

```{mermaid}
%%| label: fig-mermaid
%%| fig-width: 6
%%| fig-cap: |
%%|   A flow chart of concepts in Basis and Span 
 
flowchart TD
    A(Basis, Span <br/> Dimensions) --> B[Matrix column span]
    B-->|echelon form: <br/>columns with pivots|C[= linearly independent. <br/>Original columns (basis)<br/>span the column space]
    



```


{{< video https://www.youtube.com/watch?v=k7RM-ot2NWY&ab_channel=3Blue1Brown >}}

## Span

The **span** of two vectors $\overline v$ and $\overline w$ is the set of all linear combinations with $a*\overline v + b * \overline w$ with $a,b \in R$. 
So two operations are used: *vector scaling* and *vector addition*. 



::: {.callout-caution collapse="true"}
## Given two vectors: When can't you reach all vectors in a plane?

If the vectors are colinear/parallel or consists of points
:::


## Basis

:::{.callout-note}
The set of all linear independent vectors that span a vector space
:::


## When are vectors linear independent?

### Example

$s_1*v_1 + ...+ s_3*v_3 = 0$


\begin{pmatrix}

-2 & 1 & 4 & |& 0 \\
6 & 1 & -12 &|& 0 \\
1 & 1 & -2 &| & 0

\end{pmatrix}






If we only have trivial solution to $s_1*v_1 + ...+ s_3*v_3 = 0$ than the vectors are linearly independent.
So we solve with gaussian elimination and get the following echelon form:

\begin{pmatrix}
-2 & 1 & 4 & |& 0 \\
0 & 4 & 0 & | & 0 \\
0 & 0 & 0 & | & 0 
\end{pmatrix}

  - we se that we have a free parameter t in the $s_3$ because there is no pivot.
  - $s_3 = t$
  - $s_2 = 0$
  - $s_1 = 2t$
  